### ISSUE TITLE
[Bug] Tests fail locally at second run

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#264]
When I run `pytest` twice locally, the second time one test fails: `test_add_parameters_to_storage_xx_file`.

[error_msg.txt](https://github.com/greco-project/pvcompare/files/6188093/error_msg.txt)

Checklist to make sure that the bug report ist complete:
- [x] OS: *ubuntu*, *18.04*
- [x] Branch: *fix/release_bugs*, updated on *2021-03-23*
- [x] If applicable: Attach full error message
- [ ] If applicable: Share screenshots/images of your problem
- [ ] If applicable: Share used input data

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Checkbox is not applicable to this bug report

**Comment by MaGering** [comment]
Fixed in PR https://github.com/greco-project/pvcompare/pull/263. Can you try if you can rerun the tests multiple times now?

**Comment by SabineHaas** [comment]
Unfortunately there's another error still, error msg at second run, including `EXECUTE_TESTS_ON=master pytest`:

[error_msg_2.txt](https://github.com/greco-project/pvcompare/files/6188843/error_msg_2.txt)

**Comment by MaGering** [comment]
I hope it works now after my commit https://github.com/greco-project/pvcompare/pull/263/commits/2c931bcace607efbff523355032444b4374b5361 in PR https://github.com/greco-project/pvcompare/pull/263. For me locally it does. Could you maybe check too? Thanks! :)

**Comment by SabineHaas** [comment]
Yes, it does! Thank you :)
